//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppForSoap.ServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeClassName", Namespace="http://schemas.datacontract.org/2004/07/WCF_SOAP_Template")]
    [System.SerializableAttribute()]
    public partial class ChangeClassName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ChangeDoubleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChangeIntegerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChangeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChangeString1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ChangeDouble {
            get {
                return this.ChangeDoubleField;
            }
            set {
                if ((this.ChangeDoubleField.Equals(value) != true)) {
                    this.ChangeDoubleField = value;
                    this.RaisePropertyChanged("ChangeDouble");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChangeInteger {
            get {
                return this.ChangeIntegerField;
            }
            set {
                if ((this.ChangeIntegerField.Equals(value) != true)) {
                    this.ChangeIntegerField = value;
                    this.RaisePropertyChanged("ChangeInteger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangeString {
            get {
                return this.ChangeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeStringField, value) != true)) {
                    this.ChangeStringField = value;
                    this.RaisePropertyChanged("ChangeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangeString1 {
            get {
                return this.ChangeString1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeString1Field, value) != true)) {
                    this.ChangeString1Field = value;
                    this.RaisePropertyChanged("ChangeString1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAndTime {
            get {
                return this.DateAndTimeField;
            }
            set {
                if ((this.DateAndTimeField.Equals(value) != true)) {
                    this.DateAndTimeField = value;
                    this.RaisePropertyChanged("DateAndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VisListen", ReplyAction="http://tempuri.org/IService1/VisListenResponse")]
        ConsoleAppForSoap.ServiceRef.ChangeClassName[] VisListen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VisListen", ReplyAction="http://tempuri.org/IService1/VisListenResponse")]
        System.Threading.Tasks.Task<ConsoleAppForSoap.ServiceRef.ChangeClassName[]> VisListenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IndsætObjekt", ReplyAction="http://tempuri.org/IService1/IndsætObjektResponse")]
        void IndsætObjekt(ConsoleAppForSoap.ServiceRef.ChangeClassName temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IndsætObjekt", ReplyAction="http://tempuri.org/IService1/IndsætObjektResponse")]
        System.Threading.Tasks.Task IndsætObjektAsync(ConsoleAppForSoap.ServiceRef.ChangeClassName temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SletObjekt", ReplyAction="http://tempuri.org/IService1/SletObjektResponse")]
        void SletObjekt(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SletObjekt", ReplyAction="http://tempuri.org/IService1/SletObjektResponse")]
        System.Threading.Tasks.Task SletObjektAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RedigerObjekt", ReplyAction="http://tempuri.org/IService1/RedigerObjektResponse")]
        void RedigerObjekt(int id, ConsoleAppForSoap.ServiceRef.ChangeClassName temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RedigerObjekt", ReplyAction="http://tempuri.org/IService1/RedigerObjektResponse")]
        System.Threading.Tasks.Task RedigerObjektAsync(int id, ConsoleAppForSoap.ServiceRef.ChangeClassName temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UdregnObjekt", ReplyAction="http://tempuri.org/IService1/UdregnObjektResponse")]
        double UdregnObjekt(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UdregnObjekt", ReplyAction="http://tempuri.org/IService1/UdregnObjektResponse")]
        System.Threading.Tasks.Task<double> UdregnObjektAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleAppForSoap.ServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleAppForSoap.ServiceRef.IService1>, ConsoleAppForSoap.ServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleAppForSoap.ServiceRef.ChangeClassName[] VisListen() {
            return base.Channel.VisListen();
        }
        
        public System.Threading.Tasks.Task<ConsoleAppForSoap.ServiceRef.ChangeClassName[]> VisListenAsync() {
            return base.Channel.VisListenAsync();
        }
        
        public void IndsætObjekt(ConsoleAppForSoap.ServiceRef.ChangeClassName temp) {
            base.Channel.IndsætObjekt(temp);
        }
        
        public System.Threading.Tasks.Task IndsætObjektAsync(ConsoleAppForSoap.ServiceRef.ChangeClassName temp) {
            return base.Channel.IndsætObjektAsync(temp);
        }
        
        public void SletObjekt(int id) {
            base.Channel.SletObjekt(id);
        }
        
        public System.Threading.Tasks.Task SletObjektAsync(int id) {
            return base.Channel.SletObjektAsync(id);
        }
        
        public void RedigerObjekt(int id, ConsoleAppForSoap.ServiceRef.ChangeClassName temp) {
            base.Channel.RedigerObjekt(id, temp);
        }
        
        public System.Threading.Tasks.Task RedigerObjektAsync(int id, ConsoleAppForSoap.ServiceRef.ChangeClassName temp) {
            return base.Channel.RedigerObjektAsync(id, temp);
        }
        
        public double UdregnObjekt(int id) {
            return base.Channel.UdregnObjekt(id);
        }
        
        public System.Threading.Tasks.Task<double> UdregnObjektAsync(int id) {
            return base.Channel.UdregnObjektAsync(id);
        }
    }
}
